name: Build test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make gcc g++ libprotobuf-dev protobuf-compiler dot
          version: 1.0
      - uses: lukka/get-cmake@latest
      - run: protoc et_def.proto --proto_path et_def --cpp_out et_def
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.7
      - run: conda install protobuf==3.* setuptools pydot pytorch python-graphviz networkx
      - run: pip install fbgemm-gpu-cpu
      - run: protoc et_def.proto --proto_path et_def --python_out et_def
      - run: python3 setup.py install
      - run: python3 -m utils.et_generator.et_generator --num_npus 1
      - run: |
          set -e
          for f in *.et
          do
              python3 -m et_visualizer.et_visualizer --input_filename ${f} --output_filename "${f%.*}".dot
          done
